// Code generated by mockery 2.12.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Access is an autogenerated mock type for the Access type
type Access struct {
	mock.Mock
}

// Log provides a mock function with given fields: c, verb, metadata
func (_m *Access) Log(c echo.Context, verb string, metadata interface{}) error {
	ret := _m.Called(c, verb, metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string, interface{}) error); ok {
		r0 = rf(c, verb, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccess creates a new instance of Access. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccess(t testing.TB) *Access {
	mock := &Access{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
