// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	model "github.com/kcsu/store/model"
	mock "github.com/stretchr/testify/mock"
)

// Lookup is an autogenerated mock type for the Lookup type
type Lookup struct {
	mock.Mock
}

// ProcessGroup provides a mock function with given fields: group
func (_m *Lookup) ProcessGroup(group model.Group) error {
	ret := _m.Called(group)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLookup interface {
	mock.TestingT
	Cleanup(func())
}

// NewLookup creates a new instance of Lookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLookup(t mockConstructorTestingTNewLookup) *Lookup {
	mock := &Lookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
