// Code generated by mockery 2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/kcsu/store/model"
	mock "github.com/stretchr/testify/mock"
)

// Lookup is an autogenerated mock type for the Lookup type
type Lookup struct {
	mock.Mock
}

// ProcessGroup provides a mock function with given fields: group
func (_m *Lookup) ProcessGroup(group model.Group) error {
	ret := _m.Called(group)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
