name: Backend

on:
  push:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
      working-directory: backend
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [api, lookup, queue]
    steps:
    - uses: actions/checkout@v2
    - name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        tags: |
          type=sha
          type=edge
        images: gcr.io/kcsu/store-${{ matrix.service }}