name: Backend

on:
  push:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
      working-directory: backend
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [api, lookup, queue]
    steps:
    - uses: actions/checkout@v2
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        tags: |
          type=sha
          type=edge
        images: eu.gcr.io/kifomasy/${{ matrix.service }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./services/${{ matrix.service }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
