name: Frontend

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**

jobs:
  deploy:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_BASE_URL: /api/
          VITE_ENTS_EMAIL: entertainments@kcsu.org.uk
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          entryPoint: frontend
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIFOMASY }}'
          channelId: live
          projectId: kifomasy
